# Generated by Django 5.0.7 on 2024-10-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Argus_App', '0004_remove_mnemonicscheme_values_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMBServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='Samba-адрес сервера')),
                ('server_name', models.CharField(max_length=100, verbose_name='Samba-имя сервера')),
                ('shared_folder_name', models.CharField(max_length=100, verbose_name='Имя расшаренной папки')),
                ('file_name', models.CharField(max_length=100, verbose_name='Путь к файлу от расшаренной папки')),
            ],
            options={
                'verbose_name': 'Samba-сервер',
                'verbose_name_plural': 'Samba-сервера',
                'ordering': ['server_name'],
            },
        ),
        migrations.RemoveField(
            model_name='mnemonicscheme',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='mnemonicscheme',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='mnemonicscheme',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='mnemonicscheme',
            name='shared_folder_name',
        ),
        migrations.AddField(
            model_name='mnemonicscheme',
            name='smb_server_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemes', to='Argus_App.smbservers'),
        ),
    ]
