# Generated by Django 5.0.7 on 2024-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argus_App', '0005_smbservers_remove_mnemonicscheme_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smbservers',
            options={'verbose_name': 'Samba-сервер', 'verbose_name_plural': 'Samba-сервера'},
        ),
    ]
