# Generated by Django 5.0.7 on 2024-10-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argus_App', '0006_alter_smbservers_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smbservers',
            old_name='ip_address',
            new_name='server_ip',
        ),
        migrations.RemoveField(
            model_name='mnemonicscheme',
            name='smb_server_info',
        ),
    ]
